name: Publish

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          scope: '@thepresidentafrica'

      - name: Install dependencies
        run: npm install

      - name: Build package
        run: npm run build

      - name: Create .npmrc file
        run: echo "//npm.pkg.github.com/:_authToken=${{secrets.GH_TOKEN}}" > .npmrc
        env:
          NODE_AUTH_TOKEN: ${{secrets.GH_TOKEN }}

      - name: Publish to GitHub Container Registry
        run: npm publish --access public --registry https://npm.pkg.github.com/
        env:
          NODE_AUTH_TOKEN: ${{secrets.GH_TOKEN }}

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN }}
