name: Publish noocash SDK

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install
      - name: Publish to GitHub Container Registry
        run: |
            echo "${{ secrets.GH_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            npm config set registry https://npm.pkg.github.com
            npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
        working-directory: .
        continue-on-error: true
          
